# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, verbose_name='IP\u5730\u5740')),
                ('name', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('application', models.CharField(max_length=20, verbose_name='\u5e94\u7528')),
                ('remark', models.TextField(blank=True, max_length=50, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
